# Generated by Django 5.1.2 on 2024-10-18 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Books',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='content',
            new_name='description',
        ),
    ]
