# Generated by Django 5.1.2 on 2024-11-01 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_region_category_image_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
